In [23]:
import pandas as pd

df = pd.read_csv('../dataset/job.csv')

In [24]:
df.columns

Index(['company_name', 'job_description', 'position_title',
       'description_length', 'model_response'],
      dtype='str')

In [25]:
display(df.head(5))

,company_name,job_description,position_title,description_length,model_response
0,Google,minimum qualifications\nbachelors degree or eq...,Sales Specialist,2727,"{\n ""Core Responsibilities"": ""Responsible fo..."
1,Apple,description\nas an asc you will be highly infl...,Apple Solutions Consultant,828,"{\n ""Core Responsibilities"": ""as an asc you ..."
2,Netflix,its an amazing time to be joining netflix as w...,Licensing Coordinator - Consumer Products,3205,"{\n ""Core Responsibilities"": ""Help drive bus..."
3,Robert Half,description\n\nweb designers looking to expand...,Web Designer,2489,"{\n ""Core Responsibilities"": ""Designing webs..."
4,TrackFive,at trackfive weve got big goals were on a miss...,Web Developer,3167,"{\n ""Core Responsibilities"": ""Build and layo..."

In [26]:
jobs_to_look = ['HR','DESIGNER','INFORMATION-TECHNOLOGY',
                'TEACHER','ADVOCATE','BUSINESS-DEVELOPMENT',
                'HEALTHCARE','FITNESS','AGRICULTURE',
                'BPO','SALES','CONSULTANT','DIGITAL-MEDIA',
                'AUTOMOBILE','CHEF','FINANCE',
                'APPAREL','ENGINEERING','ACCOUNTANT',
                'CONSTRUCTION','PUBLIC-RELATIONS', 'BANKING',
                'ARTS','AVIATION']

In [27]:
for job in jobs_to_look:
    num_same = df[df['position_title'].str.lower().str.contains(job.lower(), na=False)].shape[0]
    if num_same < 3:
        jobs_to_look.remove(job)

print(f"Jobs (from resume table) with 3 or more matches in position_title (from job table): {str(jobs_to_look)}")

Jobs (from resume table) with 3 or more matches in position_title (from job table): ['HR', 'DESIGNER', 'TEACHER', 'ADVOCATE', 'HEALTHCARE', 'AGRICULTURE', 'SALES', 'CONSULTANT', 'AUTOMOBILE', 'FINANCE', 'ENGINEERING', 'ACCOUNTANT', 'CONSTRUCTION', 'BANKING', 'AVIATION']

In [28]:
# Removing unnecessary columns
df.drop(columns=['company_name','model_response'], inplace=True)

In [29]:
# Checking null strings
df.isnull().sum()

job_description       0
position_title        0
description_length    0
dtype: int64

In [30]:
df['category'] = 'no_match'

for job in jobs_to_look:
    filter = df['position_title'].str.contains(job, case=False, na=False)
    df.loc[filter, 'category'] = job

filter = df[df['category'] == 'no_match']
df = df.drop(filter.index)

print(f"Job table after removing no match jobs: {df.shape[0]}")

Job table after removing no match jobs: 191

In [32]:
display(df.head(15))

,job_description,position_title,description_length,category
0,minimum qualifications\nbachelors degree or eq...,Sales Specialist,2727,SALES
1,description\nas an asc you will be highly infl...,Apple Solutions Consultant,828,CONSULTANT
3,description\n\nweb designers looking to expand...,Web Designer,2489,DESIGNER
6,about the position\n\nthe web designer is resp...,Remote Website Designer,3471,DESIGNER
7,job description\n\nzander insurance group is o...,Web Designer,2896,DESIGNER
8,tuff is a growth marketing team working with c...,Web Designer,5143,DESIGNER
9,type of requisition regular\n\nclearance level...,SR. Web Designer,4023,DESIGNER
12,we are seeking a senior ui designer who relis...,Senior UI Designer,4484,DESIGNER
14,if youre passionate about building a better fu...,UI Web Designer,3733,DESIGNER
15,the apply with seek option will be utilized fo...,Senior Web Designer (REMOTE),4027,DESIGNER
21,company overview\n\nexechq is a consulting fir...,Chief Executive Officer - CEO Consultant,2900,CONSULTANT
23,chief executive officer healthcare\n\ncolumbu...,Chief Executive Officer - Healthcare - Columbus,2516,HEALTHCARE
32,gaming\n\nwelcome to the world of landbased ga...,Associate Software Engineering,3951,ENGINEERING
54,job summary\n\nunder general supervision this ...,Sales Executive,3896,SALES
55,position type full time\n\ntype of hire expe...,Sales Executive III Client Management,3467,SALES

In [48]:
import re
import string

df['content'] = df['position_title'] + ' ' + df['job_description']

def preprocess(txt):
    txt = str(txt).lower()
    txt = re.sub(r"http\S+", " ", txt)
    txt = re.sub(r"@\w+", " ", txt)
    txt = re.sub(r"[^a-zA-Z ]", " ", txt)
    txt = txt.translate(str.maketrans('', '', string.punctuation))
    txt = " ".join(txt.split())

    return txt

df['content'] = df['content'].apply(preprocess)

In [49]:
display(df.head(5))

,job_description,position_title,description_length,category,content
0,minimum qualifications\nbachelors degree or eq...,Sales Specialist,2727,SALES,sales specialist minimum qualifications bachel...
1,description\nas an asc you will be highly infl...,Apple Solutions Consultant,828,CONSULTANT,apple solutions consultant description as an a...
3,description\n\nweb designers looking to expand...,Web Designer,2489,DESIGNER,web designer description web designers looking...
6,about the position\n\nthe web designer is resp...,Remote Website Designer,3471,DESIGNER,remote website designer about the position the...
7,job description\n\nzander insurance group is o...,Web Designer,2896,DESIGNER,web designer job description zander insurance ...

In [50]:
save_path = '../dataset/cleaned/job.csv'
df.to_csv(save_path, index=False)

print(f"Saving job table to {save_path}")

Saving job table to dataset/cleaned/job.csv